// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq0wVwLh_bpyFnX8p4Rimd8K6O_LTIXWI',
    appId: '1:611386293758:web:c5536e32e19491a39b54af',
    messagingSenderId: '611386293758',
    projectId: 'tyremonitoringsystem-8efde',
    authDomain: 'tyremonitoringsystem-8efde.firebaseapp.com',
    storageBucket: 'tyremonitoringsystem-8efde.firebasestorage.app',
    measurementId: 'G-SBB7KTVRYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKC9NoD-XCkGFXpej4xBT0oiDXLXShS3o',
    appId: '1:611386293758:android:4b34026b6e2eed569b54af',
    messagingSenderId: '611386293758',
    projectId: 'tyremonitoringsystem-8efde',
    storageBucket: 'tyremonitoringsystem-8efde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClhwVPcRxvB0zP_TYDEjPu9-sgoSQCwq8',
    appId: '1:611386293758:ios:92f48ccedf0c78cb9b54af',
    messagingSenderId: '611386293758',
    projectId: 'tyremonitoringsystem-8efde',
    storageBucket: 'tyremonitoringsystem-8efde.firebasestorage.app',
    iosBundleId: 'com.example.tyreMs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClhwVPcRxvB0zP_TYDEjPu9-sgoSQCwq8',
    appId: '1:611386293758:ios:92f48ccedf0c78cb9b54af',
    messagingSenderId: '611386293758',
    projectId: 'tyremonitoringsystem-8efde',
    storageBucket: 'tyremonitoringsystem-8efde.firebasestorage.app',
    iosBundleId: 'com.example.tyreMs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq0wVwLh_bpyFnX8p4Rimd8K6O_LTIXWI',
    appId: '1:611386293758:web:0436cb5ef45977879b54af',
    messagingSenderId: '611386293758',
    projectId: 'tyremonitoringsystem-8efde',
    authDomain: 'tyremonitoringsystem-8efde.firebaseapp.com',
    storageBucket: 'tyremonitoringsystem-8efde.firebasestorage.app',
    measurementId: 'G-KMLC3BH8H8',
  );

}